### PR TITLE
Added new icon - PGP-key

### PR DESCRIPTION
**Pull request by adamsthws**
New icon has been added for 'PGP-key'.

It may be linked to a keystore such as: https://keys.openpgp.org

...

This PR also contains a couple of minor fixes to the ReadMe...

'Pinterest' wasn't displayed due to it being in the 5th column of the 4 column table.

Removed unnecessary word 'be'.

### CODE REVIEW

**Comment by chrede88** [comment]
Thank you for this PR. Just out of interest, is the pink color picked at random or it's associated with PGP somehow?

**Comment by chrede88** [comment]
Can you add another `css` class that's defined with all lowercase letters, like the rest of the icon classes, i.e.:

```css
.link-pgp-key, .link-PGP-Key {
  background-color: #a13c94;
}
```

**Review by chrede88 — CHANGES_REQUESTED** [review]
Can you add another `css` class that's defined with all lowercase letters, like the rest of the icon classes, i.e.:

```css
.link-pgp-key, .link-PGP-Key {
  background-color: #a13c94;
}
```

**Comment by adamsthws** [comment]
> Thank you for this PR. Just out of interest, is the pink color picked at random or it's associated with PGP somehow?

It's a random selection and I'm not attached to it (Happy to change it).

**Review by chrede88 — APPROVED** [review]

**Comment by adamsthws** [comment]
> Can you add another `css` class that's defined with all lowercase letters, like the rest of the icon classes, i.e.:
> 
> ```css
> .link-pgp-key, .link-PGP-Key {
>   background-color: #a13c94;
> }
> ```

This is done. Would you also prefer the

**Comment by chrede88** [comment]
Thank you! I'll merge this.

**Comment by adamsthws** [comment]
> Thank you! I'll merge this.

Thankyou kindly!

**Pull request merged**
