### PR TITLE
New icons added

### PR DESCRIPTION
**Pull request by adamsthws**
New icons added...

   `SSH-Key`
ssh-key

   `Certifications`
certs

   
Thankyou!
Adam

### CODE REVIEW

**Comment by chrede88** [comment]
Great, thanks.

**Comment by adamsthws** [comment]
Do you have a method for allowing external contributions to the Wiki? I ask as the list of supported icons should be also updated [here](https://github.com/chrede88/L1nkr/wiki/Supported-Icons)

**Comment by chrede88** [comment]
I'm not sure GitHub wiki allows for collaboration. I'll be sure to update the list when I publish the next release.

**Comment by adamsthws** [comment]
I’ve never used this and I don’t know if it would be of importance to you but I believe there are solutions with GitHub actions (e.g. Bi-directional Wiki Sync<https://github.com/marketplace/actions/bi-directional-wiki-sync-action>)

**Pull request merged**
